export const teams = [
  {
    id: "CSK",
    name: "Chennai Super Kings",
    shortName: "CSK",
    logo: "https://media.cricbuzz.com/cricket-flags-new/CSK.svg",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
  },
  {
    id: "DC",
    name: "Delhi Capitals",
    shortName: "DC",
    logo: "https://media.cricbuzz.com/cricket-flags-new/DC.svg",
    primaryColor: "#004C93",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "GT",
    name: "Gujarat Titans",
    shortName: "GT",
    logo: "https://media.cricbuzz.com/cricket-flags-new/GT.svg",
    primaryColor: "#7F232B",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "KKR",
    name: "Kolkata Knight Riders",
    shortName: "KKR",
    logo: "https://media.cricbuzz.com/cricket-flags-new/KKR.svg",
    primaryColor: "#2E0854",
    secondaryColor: "#FFD700",
  },
  {
    id: "LSG",
    name: "Lucknow Super Giants",
    shortName: "LSG",
    logo: "https://media.cricbuzz.com/cricket-flags-new/LSG.svg",
    primaryColor: "#0F4D92",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "MI",
    name: "Mumbai Indians",
    shortName: "MI",
    logo: "https://media.cricbuzz.com/cricket-flags-new/MI.svg",
    primaryColor: "#004BA0",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "PBKS",
    name: "Punjab Kings",
    shortName: "PBKS",
    logo: "https://media.cricbuzz.com/cricket-flags-new/PBKS.svg",
    primaryColor: "#AA4545",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "RR",
    name: "Rajasthan Royals",
    shortName: "RR",
    logo: "https://media.cricbuzz.com/cricket-flags-new/RR.svg",
    primaryColor: "#FFD700",
    secondaryColor: "#000000",
  },
  {
    id: "RCB",
    name: "Royal Challengers Bangalore",
    shortName: "RCB",
    logo: "https://media.cricbuzz.com/cricket-flags-new/RCB.svg",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
  },
  {
    id: "SRH",
    name: "Sunrisers Hyderabad",
    shortName: "SRH",
    logo: "https://media.cricbuzz.com/cricket-flags-new/SRH.svg",
    primaryColor: "#FF822A",
    secondaryColor: "#000000",
  },
]; 